#a simple chatbot made for entertainment 
# don't worry i am not selling your information😇
#Enjoy!
#⚠️Caution: Please use only small letters

#importing time module so you get time for reading 🤗

import time 

#introduction of the chatbot
print("Hello! This is Chatbot made by Jayraj")
print()
time.sleep(2)

#Introducing each other 
#asking name 

name = input("What is your Name?🤔 ")
print()
print(name+" is an interesting name 😉")
print()
time.sleep(2)

#asking age

age = int(input("What is your age? "))
print()
if age < 18:
  print("You are Young, make your present good so your future will become awesome 😉")
  print()
elif age >= 18:
  print("You are an adult now, Be Happy☺️")
  print()
else:
  ("Great!")
  print()
time.sleep(3.5)
print("I am Just 15 Years Old")
print()
time.sleep(2)

#asking mood 

mood = input("How do you feel now? ")
print()
time.sleep(2)
if mood == "happy":
  print("Great, I am glad you are happy")
  print()
elif mood == "sad":
  print("I think talking with me will make you happy😄")
  print()
elif mood == "excited":
  print("Awesome, Keep it up")
  print()
elif mood == "bored":
  print("I think talking with me will make your boring feeling destroyed☺️✌️")
  print()
elif mood == "normal":
  print("Be Awesome, You never know how awesome you are🔥")
  print()
else:
  print("So,Put a Smile on that Face")
  print()
time.sleep(3)

# asking hobbies

hobby = input("What are your hobbies? ")
time.sleep(2)
print()
print("Those are great hobbies, Keep it up")
print()
time.sleep(3)

# asking in which country do you live 

place = input("In which country do you live? ")
print()
if place == "india":
  print("Oh Wow! I also Live in India😊")
  print()
elif place == "India":
  print("Oh Wow! I also Live in India😊")
else:
  print("That's a Great place✌️")
  print()
time.sleep(2.5)

#asking user's goal of life

goal = input("What is your goal in life? ")
print()
time.sleep(3)
print("May you achieve your Goal")
print()
time.sleep(3)
print("I want to become Data Scientist 😇")
print()
time.sleep(2)

#asking favoirite food to user

food = input("What is your favourite food? ")
print()
time.sleep(2)
if food == "bhaji pav" or "bhaji pav":
  print("Wow, I also like",food)
  print()
elif food == "Chicken Biryani":
  print("Wow, I also like", food)
  print()
else:
  print("Good Choice,Well i like bhaji pav Very Much")
  print()
#asking user's favourite colour

colour = input("What is your favourite colour? ")
print()
time.sleep(2)
if colour == "blue" or "Blue":
  print("Great, I like 🔵 Blue colour🤩")
  print()
  time.sleep(2)
elif colour == "BLUE":
  print("Great, I like 🔵 Blue colour🤩")
else:
  print("I also like that colour too!")
  print()
  time.sleep(1)

sport = input("What is your Favourite sport?: ")
print()
time.sleep(1)
if sport == "cricket" or "Cricket" or "CRICKET":
  print("Oh Wow, Cricket comes in the no.1 on my hobbies list!😃")
  print()
  time.sleep(3)
elif sport == "football" or "Football" or "FootBall" or "FOOTBALL": 
  print("For me Football is very hard game 😅")
  print()
  time.sleep(2)
else:
  print("Good Choice😉")
  print()
  time.sleep(1)
  
# asking user's most used app

app = input("Which app so you use most? ")
print()
time.sleep(2)
if app == "whatsapp" or "WHATSAPP" or "WhatsApp":
  print("I use Whatsapp most")
  print()
  time.sleep(2)
  
elif app == "YouTube" or "youtube" or "Youtube" or "YOUTUBE":
  print("YouTube is my favourite app ✌🏻")
  print()
  time.sleep(2)
else:
  print("I also use" ,app, "mostly")
  print()
  time.sleep(2)
  
# asking user's favourite game

game = input("What is your favourite game 🎮 ")
print()
time.sleep(2)
if game == "wcc3" or "WCC3" or "World Cricket Championship 3":
  print("I also like WCC3 very much, I usually play WCC3 most")
  print()
  time.sleep(3)
  
elif game == "ff" or "Free Fire" or "free fire" or "FREE FIRE" or "Garena Free Fire":
  print("Free Fire is an amazing game, i play that game sometimes 😀")
  print()
  time.sleep(4.5)
else:
  print("I will try" ,game, "very soon")
  
# ending the conversation 

print("Well Dear",name,"It was a great time talking with you")
print() 
time.sleep(4)

#motivating user

print("Hey wait, I have a Quote for you…")
print()
time.sleep(3)
print("No matter your problems are so big, you have to stay strong💪")
print()
time.sleep(3)

#ending the conversation

print("I hope you also had an amazing time with me 🤗")
print()
time.sleep(3)
print("See you later,",name)
print()
print("Bye,",name)
print()
time.sleep(3)
#end of the conversation